export const countries = [
  { id: 'int', name: 'Worldwide', image: `/flags/082-united-nations.svg` },
  { id: 'ar', name: 'Argentina', image: `/flags/198-argentina.svg` },
  { id: 'at', name: 'Austria', image: `/flags/003-austria.svg` },
  { id: 'au', name: 'Australia', image: `/flags/234-australia.svg` },
  { id: 'bd', name: 'Bangladesh', image: `/flags/147-bangladesh.svg` },
  { id: 'be', name: 'Belgium', image: `/flags/165-belgium.svg` },
  { id: 'br', name: 'Brazil', image: `/flags/255-brazil.svg` },
  { id: 'ca', name: 'Canada', image: `/flags/243-canada.svg` },
  { id: 'cl', name: 'Chile', image: `/flags/131-chile.svg` },
  { id: 'cn', name: 'China', image: `/flags/034-china.svg` },
  { id: 'cz', name: 'Czech Republic', image: `/flags/149-czech-republic.svg` },
  { id: 'dk', name: 'Denmark', image: `/flags/174-denmark.svg` },
  { id: 'fi', name: 'Finland', image: `/flags/125-finland.svg` },
  { id: 'fr', name: 'France', image: `/flags/195-france.svg` },
  { id: 'de', name: 'Germany', image: `/flags/162-germany.svg` },
  { id: 'en', name: 'England', image: `/flags/216-england.svg` },
  { id: 'ab', name: 'Scotland', image: `/flags/055-scotland.svg` },
  { id: 'wl', name: 'Wales', image: `/flags/014-wales.svg` },
  { id: 'gr', name: 'Greece', image: `/flags/170-greece.svg` },
  { id: 'hk', name: 'Hong Kong', image: `/flags/183-hong-kong.svg` },
  { id: 'hu', name: 'Hungary', image: `/flags/115-hungary.svg` },
  { id: 'id', name: 'Indonesia', image: `/flags/209-indonesia.svg` },
  { id: 'ie', name: 'Ireland', image: `/flags/179-ireland.svg` },
  { id: 'in', name: 'India', image: `/flags/246-india.svg` },
  { id: 'it', name: 'Italy', image: `/flags/013-italy.svg` },
  { id: 'jp', name: 'Japan', image: `/flags/063-japan.svg` },
  { id: 'ma', name: 'Morocco', image: `/flags/166-morocco.svg` },
  { id: 'mx', name: 'Mexico', image: `/flags/252-mexico.svg` },
  { id: 'my', name: 'Malaysia', image: `/flags/118-malaysia.svg` },
  { id: 'nl', name: 'Netherlands', image: `/flags/237-netherlands.svg` },
  { id: 'no', name: 'Norway', image: `/flags/143-norway.svg` },
  { id: 'nz', name: 'New Zealand', image: `/flags/121-new-zealand.svg` },
  { id: 'pe', name: 'Peru', image: `/flags/188-peru.svg` },
  { id: 'ph', name: 'Philippines', image: `/flags/192-philippines.svg` },
  { id: 'pl', name: 'Poland', image: `/flags/211-poland.svg` },
  { id: 'pr', name: 'Puerto Rico', image: `/flags/028-puerto-rico.svg` },
  { id: 'pt', name: 'Portugal', image: `/flags/224-portugal.svg` },
  { id: 'ru', name: 'Russia', image: `/flags/248-russia.svg` },
  { id: 'sa', name: 'Saudia Arabia', image: `/flags/133-saudi-arabia.svg` },
  { id: 'se', name: 'Sweden', image: `/flags/184-sweden.svg` },
  { id: 'ch', name: 'Switzerland', image: `/flags/205-switzerland.svg` },
  { id: 'sg', name: 'Singapore', image: `/flags/230-singapore.svg` },
  { id: 'sk', name: 'Slovakia', image: `/flags/091-slovakia.svg` },
  { id: 'es', name: 'Spain', image: `/flags/128-spain.svg` },
  { id: 'tr', name: 'Turkey', image: `/flags/218-turkey.svg` },
  { id: 'us', name: 'United States', image: `/flags/226-united-states.svg` },
]

export const getCountry = (countryId) => countries.find((country) => countryId === country.id)

export const getCountries = () => countries
