export const getRegionFlag = (region) =>
  region === 'NA'
    ? 'https://octane.gg/flags/na.png'
    : region === 'EU'
    ? 'https://octane.gg/flags/eu.png'
    : region === 'OCE'
    ? 'https://octane.gg/flags/au.png'
    : region === 'SAM'
    ? 'https://octane.gg/flags/sam.png'
    : region === 'ASIA'
    ? 'https://octane.gg/flags/asia.png'
    : 'https://octane.gg/flags/int.png'

export const getRegion = (region) =>
  region === 'NA'
    ? 'North America'
    : region === 'EU'
    ? 'Europe'
    : region === 'OCE'
    ? 'Oceania'
    : region === 'SAM'
    ? 'South America'
    : region === 'ASIA'
    ? 'Asia'
    : 'International'
